import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../components/Header/Header";
import Destak from "../components/News/Destak";
import Cards from "../components/News/Cards";
export default function Home() {
  return (
    <>
      <Head>
        <title>Anderson News</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <section>
          <article className={styles.content}>
            <Destak />
          </article>
        </section>

        <section>
          <article className={styles.content}>
            <Cards />
          </article>
          <article className={styles.content}>
            <Cards variant="reverse" />
          </article>
        </section>
      </main>
    </>
  );
}
