import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../components/Header/Header";
import Destak from "../components/News/Destak";
import Cards from "../components/News/Cards";
import Link from "../components/Link/Link";
import { useEffect, useState } from "react";
import axios from "axios";

export default function Home() {
  const [articles, setArticles] = useState([]);

  useEffect(() => {
    axios
      .get("/api/search")
      .then(({ data }) => setArticles(data.articles))
      .catch((err) => console.error(err));
  }, []);

  return (
    <>
      <Head>
        <title>Anderson News</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <section>
          <article className={styles.content}>
            <Destak />
          </article>
        </section>

        <section>
          {articles.map((article, index) => (
            <article key={index} className={styles.content}>
              <Cards variant={index % 2 != 0 ? "reverse" : ""} {...article} />
            </article>
          ))}
        </section>

        <section className={styles.loadMoreSection}>
          <Link href="/" className="secondary">
            Load more
          </Link>
        </section>
      </main>
    </>
  );
}
